
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.1.0

      - name: lint
        run: npm run lint
